// Generates the index that inshellisense's loadLocalSpecsSet() expects.
//
// Contract (from vendor/inshellisense/src/runtime/runtime.ts):
//   - loadLocalSpecsSet() imports `<specs.path>/index.js`
//   - it reads `default` (spec-name array) and `diffVersionedCompletions`
//   - then resolves each name to `<specs.path>/<name>.js`
//   - it feeds the SAME mutable specSet as the bundled corpus, and runs AFTER it,
//     so any name we emit here OVERRIDES the stale bundled spec of that name.
//
// Layout: one spec per file at the TOP LEVEL of specs/src (the filename is the
// command name). Shared helpers live in specs/src/lib/ and are excluded from the
// index — directory structure is preserved by tsc, so a spec's `./lib/x.js`
// import keeps resolving after the build.
import fs from "node:fs";
import path from "node:path";

const here = path.dirname(new URL(import.meta.url).pathname);
const outDir = path.join(here, "build");

if (!fs.existsSync(outDir)) {
  console.error("specs: nothing compiled — run `tsc -p specs/tsconfig.json` first");
  process.exit(1);
}

const names = fs
  .readdirSync(outDir, { withFileTypes: true })
  .filter((e) => e.isFile() && e.name.endsWith(".js") && e.name !== "index.js")
  .map((e) => path.basename(e.name, ".js"))
  .sort();

if (names.length === 0) {
  console.error("specs: compiled output contained no top-level spec files");
  process.exit(1);
}

fs.writeFileSync(
  path.join(outDir, "index.js"),
  `// GENERATED by specs/build-index.mjs — do not edit.\n` +
    `export default ${JSON.stringify(names, null, 2)};\n` +
    `export const diffVersionedCompletions = [];\n`,
);

// Mark the folder as ESM so Node imports our `export default` specs correctly.
// Upstream writes the same file into ~/.inshellisense/spec.
fs.writeFileSync(path.join(outDir, "package.json"), JSON.stringify({ type: "module" }));

console.log(`specs: indexed ${names.length} spec(s) -> ${outDir}`);
for (const n of names) console.log(`  - ${n}`);
